version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:1-10.0-bookworm
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MESSConnection: "Host=db;Port=5432;Database=mess;Username=mess;Password=MessDevPassword_123!"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: "mess"
      POSTGRES_PASSWORD: "MessDevPassword_123!"
      POSTGRES_DB: "mess"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: