// <auto-generated />
using System;
using MESS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESS.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260309190157_AddingLocationModel")]
    partial class AddingLocationModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESS.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MESS.Data.Models.PartDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartDefinitions");
                });

            modelBuilder.Entity("MESS.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartDefinitionId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FromBatchOf")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WorkInstructionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogPart", b =>
                {
                    b.Property<int>("ProductionLogId")
                        .HasColumnType("int");

                    b.Property<int>("SerializablePartId")
                        .HasColumnType("int");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.HasKey("ProductionLogId", "SerializablePartId", "OperationType");

                    b.HasIndex("SerializablePartId");

                    b.ToTable("ProductionLogParts");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLogId")
                        .HasColumnType("int");

                    b.Property<int>("WorkInstructionStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLogId");

                    b.HasIndex("WorkInstructionStepId");

                    b.ToTable("ProductionLogSteps");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStepAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionLogStepId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmitTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLogStepId");

                    b.ToTable("ProductionLogStepAttempts");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PartDefinitionId");

                    b.ToTable("SerializableParts");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("int");

                    b.Property<int?>("PartProducedId")
                        .HasColumnType("int");

                    b.Property<bool>("PartProducedIsSerialized")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldGenerateQrCode")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalId");

                    b.HasIndex("PartProducedId");

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstructionNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("WorkInstructionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("WorkInstructionNodes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ProductWorkInstruction", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkInstructionsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "WorkInstructionsId");

                    b.HasIndex("WorkInstructionsId");

                    b.ToTable("ProductWorkInstruction");
                });

            modelBuilder.Entity("MESS.Data.Models.PartNode", b =>
                {
                    b.HasBaseType("MESS.Data.Models.WorkInstructionNode");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("int");

                    b.HasIndex("PartDefinitionId");

                    b.ToTable("PartNodes", (string)null);
                });

            modelBuilder.Entity("MESS.Data.Models.Step", b =>
                {
                    b.HasBaseType("MESS.Data.Models.WorkInstructionNode");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailedBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PrimaryMedia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("SecondaryMedia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("MESS.Data.Models.Product", b =>
                {
                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.Product", "PartDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.HasOne("MESS.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.WorkInstruction", "WorkInstruction")
                        .WithMany()
                        .HasForeignKey("WorkInstructionId");

                    b.Navigation("Product");

                    b.Navigation("WorkInstruction");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogPart", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLog", "ProductionLog")
                        .WithMany()
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.SerializablePart", "SerializablePart")
                        .WithMany("ProductionLogParts")
                        .HasForeignKey("SerializablePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLog");

                    b.Navigation("SerializablePart");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLog", "ProductionLog")
                        .WithMany("LogSteps")
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.Step", "WorkInstructionStep")
                        .WithMany()
                        .HasForeignKey("WorkInstructionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLog");

                    b.Navigation("WorkInstructionStep");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStepAttempt", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLogStep", "ProductionLogStep")
                        .WithMany("Attempts")
                        .HasForeignKey("ProductionLogStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLogStep");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.HasOne("MESS.Data.Models.Location", "Location")
                        .WithMany("SerializableParts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithMany()
                        .HasForeignKey("PartDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstruction", "Original")
                        .WithMany()
                        .HasForeignKey("OriginalId");

                    b.HasOne("MESS.Data.Models.PartDefinition", "PartProduced")
                        .WithMany()
                        .HasForeignKey("PartProducedId");

                    b.Navigation("Original");

                    b.Navigation("PartProduced");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstructionNode", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstruction", null)
                        .WithMany("Nodes")
                        .HasForeignKey("WorkInstructionId");
                });

            modelBuilder.Entity("ProductWorkInstruction", b =>
                {
                    b.HasOne("MESS.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.WorkInstruction", null)
                        .WithMany()
                        .HasForeignKey("WorkInstructionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESS.Data.Models.PartNode", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstructionNode", null)
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.PartNode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithMany()
                        .HasForeignKey("PartDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.Step", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstructionNode", null)
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.Step", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESS.Data.Models.Location", b =>
                {
                    b.Navigation("SerializableParts");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.Navigation("LogSteps");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.Navigation("ProductionLogParts");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
