// <auto-generated />
using System;
using System.Collections.Generic;
using MESS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MESS.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260416164824_AddingProductionLogPartRelationshipsView")]
    partial class AddingProductionLogPartRelationshipsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FailureAdjectiveFailureNoun", b =>
                {
                    b.Property<int>("AdjectivesId")
                        .HasColumnType("integer");

                    b.Property<int>("NounsId")
                        .HasColumnType("integer");

                    b.HasKey("AdjectivesId", "NounsId");

                    b.HasIndex("NounsId");

                    b.ToTable("FailureNounAdjectives", (string)null);
                });

            modelBuilder.Entity("MESS.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<int>>("ProductionLogIds")
                        .HasColumnType("integer[]");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MESS.Data.Models.FailureAdjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FailureAdjective");
                });

            modelBuilder.Entity("MESS.Data.Models.FailureNoun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FailureNoun");
                });

            modelBuilder.Entity("MESS.Data.Models.PartDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSerialNumberUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Number\" IS NULL OR \"Number\" = ''");

                    b.HasIndex("Name", "Number")
                        .IsUnique();

                    b.ToTable("PartDefinitions");
                });

            modelBuilder.Entity("MESS.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartDefinitionId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromBatchOf")
                        .HasColumnType("integer");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorId")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkInstructionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogPart", b =>
                {
                    b.Property<int>("ProductionLogId")
                        .HasColumnType("integer");

                    b.Property<int>("SerializablePartId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.HasKey("ProductionLogId", "SerializablePartId", "OperationType");

                    b.HasIndex("SerializablePartId");

                    b.ToTable("ProductionLogParts");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLogId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkInstructionStepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLogId");

                    b.HasIndex("WorkInstructionStepId");

                    b.ToTable("ProductionLogSteps");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStepAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductionLogStepId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLogStepId");

                    b.ToTable("ProductionLogStepAttempts");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartDefinitionId");

                    b.ToTable("SerializableParts");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePartRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildPartId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentPartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildPartId")
                        .IsUnique();

                    b.HasIndex("ParentPartId");

                    b.ToTable("SerializablePartRelationships");
                });

            modelBuilder.Entity("MESS.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SerializablePartId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SerializablePartId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MESS.Data.Models.TagHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("SerializablePartId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SerializablePartId");

                    b.HasIndex("TagId");

                    b.ToTable("TagHistories");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("integer");

                    b.Property<int?>("PartProducedId")
                        .HasColumnType("integer");

                    b.Property<bool>("PartProducedIsSerialized")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldGenerateQrCode")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OriginalId");

                    b.HasIndex("PartProducedId");

                    b.HasIndex("Title", "Version")
                        .IsUnique();

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstructionNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkInstructionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkInstructionId");

                    b.ToTable("WorkInstructionNodes");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductWorkInstruction", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkInstructionsId")
                        .HasColumnType("integer");

                    b.HasKey("ProductsId", "WorkInstructionsId");

                    b.HasIndex("WorkInstructionsId");

                    b.ToTable("ProductWorkInstruction");
                });

            modelBuilder.Entity("MESS.Data.Models.PartNode", b =>
                {
                    b.HasBaseType("MESS.Data.Models.WorkInstructionNode");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<int>("PartDefinitionId")
                        .HasColumnType("integer");

                    b.HasIndex("PartDefinitionId");

                    b.ToTable("PartNodes", (string)null);
                });

            modelBuilder.Entity("MESS.Data.Models.Step", b =>
                {
                    b.HasBaseType("MESS.Data.Models.WorkInstructionNode");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailedBody")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PrimaryMedia")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("SecondaryMedia")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("FailureAdjectiveFailureNoun", b =>
                {
                    b.HasOne("MESS.Data.Models.FailureAdjective", null)
                        .WithMany()
                        .HasForeignKey("AdjectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.FailureNoun", null)
                        .WithMany()
                        .HasForeignKey("NounsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESS.Data.Models.Product", b =>
                {
                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.Product", "PartDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.HasOne("MESS.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.WorkInstruction", "WorkInstruction")
                        .WithMany()
                        .HasForeignKey("WorkInstructionId");

                    b.Navigation("Product");

                    b.Navigation("WorkInstruction");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogPart", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLog", "ProductionLog")
                        .WithMany()
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.SerializablePart", "SerializablePart")
                        .WithMany("ProductionLogParts")
                        .HasForeignKey("SerializablePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLog");

                    b.Navigation("SerializablePart");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLog", "ProductionLog")
                        .WithMany("LogSteps")
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.Step", "WorkInstructionStep")
                        .WithMany()
                        .HasForeignKey("WorkInstructionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLog");

                    b.Navigation("WorkInstructionStep");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStepAttempt", b =>
                {
                    b.HasOne("MESS.Data.Models.ProductionLogStep", "ProductionLogStep")
                        .WithMany("Attempts")
                        .HasForeignKey("ProductionLogStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLogStep");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithMany()
                        .HasForeignKey("PartDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePartRelationship", b =>
                {
                    b.HasOne("MESS.Data.Models.SerializablePart", "ChildPart")
                        .WithOne("ParentRelationship")
                        .HasForeignKey("MESS.Data.Models.SerializablePartRelationship", "ChildPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.SerializablePart", "ParentPart")
                        .WithMany("ChildrenRelationships")
                        .HasForeignKey("ParentPartId");

                    b.Navigation("ChildPart");

                    b.Navigation("ParentPart");
                });

            modelBuilder.Entity("MESS.Data.Models.Tag", b =>
                {
                    b.HasOne("MESS.Data.Models.SerializablePart", "SerializablePart")
                        .WithMany()
                        .HasForeignKey("SerializablePartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SerializablePart");
                });

            modelBuilder.Entity("MESS.Data.Models.TagHistory", b =>
                {
                    b.HasOne("MESS.Data.Models.SerializablePart", null)
                        .WithMany()
                        .HasForeignKey("SerializablePartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MESS.Data.Models.Tag", "Tag")
                        .WithMany("History")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstruction", "Original")
                        .WithMany()
                        .HasForeignKey("OriginalId");

                    b.HasOne("MESS.Data.Models.PartDefinition", "PartProduced")
                        .WithMany()
                        .HasForeignKey("PartProducedId");

                    b.Navigation("Original");

                    b.Navigation("PartProduced");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstructionNode", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstruction", null)
                        .WithMany("Nodes")
                        .HasForeignKey("WorkInstructionId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MESS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MESS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MESS.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductWorkInstruction", b =>
                {
                    b.HasOne("MESS.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.WorkInstruction", null)
                        .WithMany()
                        .HasForeignKey("WorkInstructionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESS.Data.Models.PartNode", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstructionNode", null)
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.PartNode", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MESS.Data.Models.PartDefinition", "PartDefinition")
                        .WithMany()
                        .HasForeignKey("PartDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartDefinition");
                });

            modelBuilder.Entity("MESS.Data.Models.Step", b =>
                {
                    b.HasOne("MESS.Data.Models.WorkInstructionNode", null)
                        .WithOne()
                        .HasForeignKey("MESS.Data.Models.Step", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLog", b =>
                {
                    b.Navigation("LogSteps");
                });

            modelBuilder.Entity("MESS.Data.Models.ProductionLogStep", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("MESS.Data.Models.SerializablePart", b =>
                {
                    b.Navigation("ChildrenRelationships");

                    b.Navigation("ParentRelationship");

                    b.Navigation("ProductionLogParts");
                });

            modelBuilder.Entity("MESS.Data.Models.Tag", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("MESS.Data.Models.WorkInstruction", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
